#! /bin/sh

set -x

# Generate config.h.in from acconfig.h and configure.in
autoheader

# Generate configure script
autoconf


## The part below will be necessary until we cleanup the actual mess in
## module's build system

set +x

# Generate MODULE_config.h.in from configure.in
for MODULEPATH in src/mod/*.mod; do
	if [ -f $MODULEPATH/configure.in ]; then
		set -x
		cd $MODULEPATH
		autoheader
		cd ../../..
		set +x
	fi
done

set -x

# Generate configure scripts for modules
misc/modconfig --top_srcdir=. eggautoconf

