#! /bin/sh
#
# $Id: bootstrap,v 1.5 2001/10/10 01:20:08 ite Exp $
#
# Recommended development tools versions:
#   autoconf 2.52
#   automake 1.5
#   libtool 1.4.2
# Please note that it may happen that the bootstrap process reports errors.
# This doesn't necessarily mean that something went wrong. Try if ./configure
# and make run without any unexpected errors before reporting bugs. And of
# course make sure you have the tool's versions above installed before
# bootstrapping the package. If you don't have them, you can alternatively
# download the prepackaged and already bootstrapped current CVS snapshot (
# daily resynched) from ftp.eggheads.org.
#
# ITE

set -x

# Bring gettext files
#gettextize --copy --force

# Generate aclocal.m4 from misc/*.m4 files
aclocal -I .

# Bring in libtool with libtdl abstraction
libtoolize --force --copy --ltdl

# Generate config.h.in from acconfig.h and configure.in
autoheader

# Generate Makefile.in from Makefile.am
automake --add-missing --copy

# Generate configure script
autoconf

# Remove previous config.cache
if [ -f config.cache ]; then
  rm -f config.cache
fi

set -x
