chat: chat.c linemode.c zipmode.c my_socket.c sockbuf.c
	gcc chat.c linemode.c zipmode.c my_socket.c sockbuf.c -lz -g -o chat

client: client.c linemode.c zipmode.c my_socket.c sockbuf.c
	gcc client.c linemode.c zipmode.c my_socket.c sockbuf.c -lz -g -o client
